//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_cast
    {
        public int Actor_ID { get; set; }
        public int Movie_ID { get; set; }
        public string Cast { get; set; }
    }
}
