//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int Movie_ID { get; set; }
        public string Title { get; set; }
        public byte[] Cover_img { get; set; }
        public string Description { get; set; }
        public DateTime Release_date { get; set; }
    }
}
