//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TvShowComment
    {
        public int TvCommentId { get; set; }
        public string TvComments { get; set; }
        public Nullable<int> TvRating { get; set; }
        public Nullable<int> TvShowId { get; set; }
    }
}
